name: Process Recurring Donations

on:
  schedule:
    - cron: '0 1 * * *'  # Run at 1 AM UTC daily
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  process-donations:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BUCKAROO_WEBSITE_KEY: ${{ secrets.BUCKAROO_WEBSITE_KEY }}
      BUCKAROO_SECRET_KEY: ${{ secrets.BUCKAROO_SECRET_KEY }}
      BUCKAROO_TEST_MODE: ${{ secrets.BUCKAROO_TEST_MODE }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Compile TypeScript
        run: npx tsc --project tsconfig.scripts.json

      - name: Process recurring donations
        run: node dist/scripts/process-recurring-donations.js